version: "3.9"
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""   # root sin pass
      MYSQL_DATABASE: runnconnect
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql   # Persistencia local

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ""   # root sin pass
    depends_on:
      - mysql-db
